env:
  global:
  - VOTE_APP=vote
  - RESULT_APP=result
  - WORKER_APP=worker
  - VOTE_REPO=kurtcrowley/tek-voting-vote
  - COMMIT=${TRAVIS_COMMIT::8}


sudo: required

services:
  - docker

jobs:
  include:
    - stage: VOTE
      script: 
      - cd vote
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -f Dockerfile -t vote .
      - docker push vote
    - stage: RESULT
      script: 
      - cd vote
      - docker build -t result -f Dockerfile .
    - stage: WORKER
      script: 
      - cd worker
      - docker build -t worker -f Dockerfile .
