sudo: required

language: python

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo $TRAVIS_BUILD_DIR 
      - cd vote
      - echo $TRAVIS_BUILD_DIR
      - docker build -t vote -f Dockerfile .
      - docker images
