sudo: required

language: python

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo $TRAVIS_BUILD_DIR
      - docker build -f vote/Dockerfile .
      - docker images
