sudo: required

services:
  - docker

jobs:
  include:
    - stage: VOTE
      script: 
      - cd vote
      - docker build -t vote -f Dockerfile .
      - docker images
    - stage: RESULT
      script: 
      - cd vote
      - docker build -t result -f Dockerfile .
    - stage: WORKER
      script: 
      - cd worker
      - docker build -t worker -f Dockerfile .
