apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
spec:
  template:
    metadata:
      labels:
        app: votingapp
        component: result
    spec:  
      containers:
      - name: result
        image: kurtcrowley/tek-voting-result:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
